apiVersion: apps/v1
kind: Deployment
metadata:
  name: mileage
  labels:
    app: mileage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mileage
  template:
    metadata:
      labels:
        app: mileage
    spec:
      containers:
        - name: mileage
          image: username/mileage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5